"""add_enterprise_features

Revision ID: 3fe0513251df
Revises: 
Create Date: 2026-02-23 10:24:06.476381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fe0513251df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success_metric', sa.String(length=50), nullable=True),
    sa.Column('min_sample_size', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('winner_variant_id', sa.String(length=50), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_tests_client_slug'), 'ab_tests', ['client_slug'], unique=False)
    op.create_index(op.f('ix_ab_tests_id'), 'ab_tests', ['id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_client_slug'), 'consents', ['client_slug'], unique=False)
    op.create_index(op.f('ix_consents_contact_phone'), 'consents', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_consents_id'), 'consents', ['id'], unique=False)
    op.create_table('conversation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('ai_messages', sa.Integer(), nullable=True),
    sa.Column('user_messages', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('transfer_requested', sa.Boolean(), nullable=True),
    sa.Column('transfer_reason', sa.String(length=255), nullable=True),
    sa.Column('products_shown', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('products_interested', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('tools_used', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tools_count', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_metrics_client_slug'), 'conversation_metrics', ['client_slug'], unique=False)
    op.create_index(op.f('ix_conversation_metrics_conversation_id'), 'conversation_metrics', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_metrics_id'), 'conversation_metrics', ['id'], unique=False)
    op.create_table('crm_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('auto_create_contacts', sa.Boolean(), nullable=True),
    sa.Column('auto_create_deals', sa.Boolean(), nullable=True),
    sa.Column('sync_notes', sa.Boolean(), nullable=True),
    sa.Column('sync_on_transfer', sa.Boolean(), nullable=True),
    sa.Column('default_pipeline_id', sa.String(length=100), nullable=True),
    sa.Column('default_stage_id', sa.String(length=100), nullable=True),
    sa.Column('converted_stage_id', sa.String(length=100), nullable=True),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_configs_client_slug'), 'crm_configs', ['client_slug'], unique=True)
    op.create_index(op.f('ix_crm_configs_id'), 'crm_configs', ['id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('new_conversations', sa.Integer(), nullable=True),
    sa.Column('resolved_conversations', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('ai_messages', sa.Integer(), nullable=True),
    sa.Column('user_messages', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('transfers', sa.Integer(), nullable=True),
    sa.Column('abandoned', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('avg_conversation_length', sa.Float(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('avg_lead_score', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('transfer_rate', sa.Float(), nullable=True),
    sa.Column('resolution_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_client_slug'), 'daily_stats', ['client_slug'], unique=False)
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    op.create_table('data_processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('data_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legal_basis', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_processing_logs_client_slug'), 'data_processing_logs', ['client_slug'], unique=False)
    op.create_index(op.f('ix_data_processing_logs_id'), 'data_processing_logs', ['id'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('conversation_retention_days', sa.Integer(), nullable=True),
    sa.Column('analytics_retention_days', sa.Integer(), nullable=True),
    sa.Column('logs_retention_days', sa.Integer(), nullable=True),
    sa.Column('anonymize_after_days', sa.Integer(), nullable=True),
    sa.Column('auto_anonymize', sa.Boolean(), nullable=True),
    sa.Column('auto_delete_on_request', sa.Boolean(), nullable=True),
    sa.Column('deletion_delay_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_client_slug'), 'data_retention_policies', ['client_slug'], unique=True)
    op.create_index(op.f('ix_data_retention_policies_id'), 'data_retention_policies', ['id'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_file_url', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_client_slug'), 'data_subject_requests', ['client_slug'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_contact_phone'), 'data_subject_requests', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_id'), 'data_subject_requests', ['id'], unique=False)
    op.create_table('rate_limit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_logs_client_slug'), 'rate_limit_logs', ['client_slug'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_created_at'), 'rate_limit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_id'), 'rate_limit_logs', ['id'], unique=False)
    op.create_table('ab_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.String(length=50), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('transferred', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['ab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_results_conversation_id'), 'ab_test_results', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ab_test_results_id'), 'ab_test_results', ['id'], unique=False)
    op.create_index(op.f('ix_ab_test_results_test_id'), 'ab_test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_ab_test_results_variant_id'), 'ab_test_results', ['variant_id'], unique=False)
    op.create_table('product_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_slug', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('interests', sa.Integer(), nullable=True),
    sa.Column('inquiries', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_slug'], ['clients.slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_analytics_client_slug'), 'product_analytics', ['client_slug'], unique=False)
    op.create_index(op.f('ix_product_analytics_date'), 'product_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_product_analytics_id'), 'product_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_product_analytics_product_id'), 'product_analytics', ['product_id'], unique=False)
    op.alter_column('ai_config', 'split_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_config', 'intent_detection_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_config', 'intent_detection_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'keywords'::character varying"),
               existing_nullable=True)
    op.alter_column('ai_config', 'split_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'smart'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_product_analytics_product_id'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_id'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_date'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_client_slug'), table_name='product_analytics')
    op.drop_table('product_analytics')
    op.drop_index(op.f('ix_ab_test_results_variant_id'), table_name='ab_test_results')
    op.drop_index(op.f('ix_ab_test_results_test_id'), table_name='ab_test_results')
    op.drop_index(op.f('ix_ab_test_results_id'), table_name='ab_test_results')
    op.drop_index(op.f('ix_ab_test_results_conversation_id'), table_name='ab_test_results')
    op.drop_table('ab_test_results')
    op.drop_index(op.f('ix_rate_limit_logs_id'), table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_created_at'), table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_client_slug'), table_name='rate_limit_logs')
    op.drop_table('rate_limit_logs')
    op.drop_index(op.f('ix_data_subject_requests_id'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_contact_phone'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_client_slug'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_data_retention_policies_id'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_client_slug'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index(op.f('ix_data_processing_logs_id'), table_name='data_processing_logs')
    op.drop_index(op.f('ix_data_processing_logs_client_slug'), table_name='data_processing_logs')
    op.drop_table('data_processing_logs')
    op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_client_slug'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_crm_configs_id'), table_name='crm_configs')
    op.drop_index(op.f('ix_crm_configs_client_slug'), table_name='crm_configs')
    op.drop_table('crm_configs')
    op.drop_index(op.f('ix_conversation_metrics_id'), table_name='conversation_metrics')
    op.drop_index(op.f('ix_conversation_metrics_conversation_id'), table_name='conversation_metrics')
    op.drop_index(op.f('ix_conversation_metrics_client_slug'), table_name='conversation_metrics')
    op.drop_table('conversation_metrics')
    op.drop_index(op.f('ix_consents_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_contact_phone'), table_name='consents')
    op.drop_index(op.f('ix_consents_client_slug'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_ab_tests_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_client_slug'), table_name='ab_tests')
    op.drop_table('ab_tests')
    # ### end Alembic commands ###
